site_name: Notes
nav:
  - Home: 'index.md'
  - MkDocs: mkdocs.md
  - Javascript: js.md
  - CSS: css.md
  - MEAN: mean.md
  - Angular: ng.md
  - MERN: mern.md
  - React: react.md
  - Google Cloud: gcloud.md
theme: windmill-dark
